version: '3.1'
services:
  database:
    restart: always
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=qeude
      - POSTGRES_PASS=qeude
      - POSTGRES_DB=timesup
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin #you can change this
    depends_on:
      - database
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always
volumes:
  database-data: # named volumes can be managed easier using docker-compose