# Generated by Django 3.1.4 on 2021-01-04 11:33

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("timesup", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="round",
        ),
        migrations.AddField(
            model_name="game",
            name="state",
            field=django_fsm.FSMField(default="created", max_length=50, protected=True),
        ),
        migrations.AlterUniqueTogether(
            name="card",
            unique_together={("word",)},
        ),
    ]
